# Generated by Django 3.1.1 on 2020-09-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deuda', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('pagado', models.BooleanField()),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('nombre_familiar', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('cargado', models.DateField(auto_now_add=True)),
                ('desc_familia', models.BooleanField()),
                ('discapacidad', models.BooleanField()),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('veces', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default='')),
                ('dias', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('horario', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('inscripcion', models.DateField(auto_now_add=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/alumnos')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
    ]
