# Generated by Django 3.1.1 on 2020-09-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichero_alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre_familiar',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
