# Generated by Django 3.1.1 on 2020-09-28 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichero_alumnos', '0003_auto_20200927_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='inscripcion',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='cargado',
            field=models.DateField(verbose_name=datetime.datetime.now),
        ),
    ]
