# Generated by Django 3.1.1 on 2020-09-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichero_alumnos', '0004_auto_20200927_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='nacimiento',
            field=models.CharField(blank=True, help_text='01/01/2001', max_length=30, null=True),
        ),
    ]
