# Generated by Django 3.1.1 on 2020-09-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichero_alumnos', '0005_auto_20200927_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='cargado',
            field=models.DateField(auto_now_add=True),
        ),
    ]
