# Generated by Django 3.1.1 on 2020-09-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichero_alumnos', '0006_auto_20200927_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='actividad',
            field=models.CharField(choices=[('Bebes', 'Bebes'), ('Escuelita', 'Escuelita'), ('AquaGym', 'AquaGym'), ('AquaFitness', 'AquaFitness')], default='', max_length=30),
        ),
    ]
