# Generated by Django 3.1.1 on 2020-09-28 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichero_alumnos', '0007_alumno_actividad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='nombre_familiar',
            new_name='familiar_nombre',
        ),
    ]
