# Generated by Django 3.1.1 on 2020-09-29 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichero_alumnos', '0009_auto_20200929_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='cuarta',
            new_name='cl1',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='decima',
            new_name='cl10',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='novena',
            new_name='cl2',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='octava',
            new_name='cl3',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='primera',
            new_name='cl4',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='quinta',
            new_name='cl5',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='segunda',
            new_name='cl6',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='septima',
            new_name='cl7',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='sexta',
            new_name='cl8',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='tercera',
            new_name='cl9',
        ),
    ]
