# Generated by Django 3.1.1 on 2020-09-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichero_alumnos', '0010_auto_20200929_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='deuda',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
