# Generated by Django 3.1.1 on 2020-09-29 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichero_alumnos', '0012_auto_20200929_1414'),
    ]

   
