# Generated by Django 3.1.1 on 2020-09-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichero_alumnos', '0013_remove_alumno_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fecha_pago',
            field=models.DateField(),
        ),
    ]
