# Generated by Django 3.1.1 on 2020-09-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichero_alumnos', '0014_auto_20200929_1542'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='alumno',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
