# Generated by Django 3.1.1 on 2020-10-04 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichero_alumnos', '0016_alumno_octubre2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'verbose_name': 'Alumno(ORIGINAL!!)', 'verbose_name_plural': 'Alumnos(ORIGINAL!!)'},
        ),
    ]
