# Generated by Django 3.1.1 on 2020-10-04 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichero_alumnos', '0018_auto_20201004_0916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno_noviembre2020',
        ),
    ]
