# Generated by Django 3.1.1 on 2020-10-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichero_alumnos', '0019_delete_alumno_noviembre2020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumno_octubre2020',
            new_name='Alumno_mes',
        ),
        migrations.AlterModelOptions(
            name='alumno_mes',
            options={'verbose_name': 'Alumno_mes', 'verbose_name_plural': 'Alumnos_mes'},
        ),
    ]
