# Generated by Django 3.1.1 on 2020-10-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichero_alumnos', '0020_auto_20201004_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, default='', help_text='0000 012345', max_length=30, null=True),
        ),
    ]
