# Generated by Django 3.1.1 on 2020-10-31 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichero_alumnos', '0023_auto_20201030_1402'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
