# Generated by Django 3.1.1 on 2020-10-31 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichero_alumnos', '0024_delete_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('edad', models.IntegerField(blank=True, default='', null=True)),
                ('familiar_nombre', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, default='', help_text='0000  012345', max_length=30, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('nacimiento', models.CharField(blank=True, help_text='01/01/2001', max_length=30, null=True)),
                ('cargado', models.DateField(auto_now_add=True)),
                ('desc_familia', models.BooleanField()),
                ('discapacidad', models.BooleanField()),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('horario', models.CharField(blank=True, default='', help_text='00dia  /  00dia', max_length=30, null=True)),
                ('actividad', models.CharField(choices=[('Bebes', 'Bebes'), ('Escuelita', 'Escuelita'), ('AquaGym', 'AquaGym'), ('AquaFitness', 'AquaFitness')], default='', max_length=30)),
                ('deuda', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('cl1', models.BooleanField()),
                ('cl2', models.BooleanField()),
                ('cl3', models.BooleanField()),
                ('cl4', models.BooleanField()),
                ('cl5', models.BooleanField()),
                ('cl6', models.BooleanField()),
                ('cl7', models.BooleanField()),
                ('cl8', models.BooleanField()),
                ('cl9', models.BooleanField()),
                ('cl10', models.BooleanField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/alumnos')),
            ],
            options={
                'verbose_name': 'Alumno(ORIGINAL!!)',
                'verbose_name_plural': 'Alumnos(ORIGINAL!!)',
            },
        ),
        migrations.DeleteModel(
            name='Alumno_mes',
        ),
    ]
