# Generated by Django 3.1.1 on 2020-10-31 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichero_alumnos', '0025_auto_20201031_0011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
    ]
